
services:
  # Run the dev bot with hot reloading of local files
  dev:
    container_name: rollbot_dev
    image: rollbot_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.dev
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    tmpfs:
      - /tmp
    user: '${UID:-1000}:${GID:-1000}'
    restart: unless-stopped