FROM oven/bun

ENV NODE_ENV=development

# Since the entire working dir will be mounted, we can't install deps here
WORKDIR /app

# Make sure deps are installed & start the app in watch mode
CMD ["sh", "-c", "bun install && bun --watch ."]